spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/wn_mall
      username: postgres
      password: forever
  redis:
    host: 192.168.11.157
    port: 6379
  mail:
    host: smtp.qq.com
    username: 447641244@qq.com
    password: tytwaheujzwsbiai
  rabbitmq:
    host: 192.168.11.157
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
mybatis-plus:
  global-config:
    db-config:
      table-prefix: mall_
      id-type: auto
      logic-delete-field: isDel
      logic-delete-value: y
      logic-not-delete-value: n

  type-aliases-package: com.woniuxy.mall.entity
logging:
  level:
    com.woniuxy.mall:
      mapper: debug
      web: debug
      filter: debug
JWT:
  secretKey: 123456
minio:
  endpoint: http://192.168.11.157:9000
  AccessKey: minioadmin
  secretKey: minioadmin
  bucketName: goods