spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/wn_mall
      username: postgres
      password: forever
mybatis-plus:
  global-config:
    db-config:
      table-prefix: mall_
      id-type: auto
      logic-delete-field: isDel
      logic-delete-value: n
      logic-not-delete-value: y
logging:
  level:
    com.woniuxy.mall.mapper: debug
